name: CI

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.sql'
      - '.github/workflows/ci.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Unit tests
        run: bun run test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Cypress run
        run: bunx cypress run || true
