name: Component Map

on:
  push:
    paths:
      - 'src/components/**/*.{tsx,ts,jsx,js}'
      - '.github/workflows/component-map.yml'
  pull_request:
    paths:
      - 'src/components/**/*.{tsx,ts,jsx,js}'
      - '.github/workflows/component-map.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g madge
      - name: Generate graph
        run: |
          madge --json src/components > graph.json
          node scripts/jsonToMermaid.mjs graph.json > docs/component-graph.mmd
      - name: Commit graph
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/component-graph.mmd'
          message: 'ci: update component map'
          default_author: github_actions
          push: true
          branch: ${{ github.head_ref || github.ref_name }}
