on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
  workflow_dispatch:

name: Deploy Supabase Edge Functions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Functions
        run: |
          supabase login --service-role $SUPABASE_ACCESS_TOKEN
          supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
