name: Generate bun.lockb

on:
  workflow_dispatch:      # manual trigger
  push:
    paths:
      - "package.json"    # auto-re-run if deps change
      - ".github/workflows/generate-lockfile.yml"

jobs:
  build-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # needed so the workflow can push
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the PR branch, not a detached HEAD
          ref: ${{ github.head_ref }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps & build lockfile
        run: bun install

      - name: Commit and push lockfile if changed
        run: |
          if [[ -n $(git status --porcelain bun.lockb) ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bun.lockb
            git commit -m "chore: regenerate bun.lockb"
            git push
          else
            echo "bun.lockb already up to date"
          fi
