name: Run Supabase Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply database migrations
        run: |
          supabase db push \
            --db-url "${{ secrets.SUPABASE_DB_URL }}" \
            --dns-resolver https

      - name: Show migration status
        run: |
          supabase db status \
            --db-url "${{ secrets.SUPABASE_DB_URL }}" \
            --dns-resolver https
