name: Run Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply database migrations
        # We pass in the full DB URL so no interactive prompt is required
        run: supabase db push --db-url "${{ secrets.SUPABASE_DB_URL }}"

      - name: Show migration status
        run: supabase db status --db-url "${{ secrets.SUPABASE_DB_URL }}"
