name: Run Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Postgres client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Apply SQL migrations via psql
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "Testing connection…"
          psql "$DATABASE_URL" -c '\conninfo'
          
          for f in supabase/migrations/*.sql; do
            echo "Applying $f"
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
