name: Run Supabase Migrations

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:       # manual trigger from the Actions tab

jobs:
  migrate:
    runs-on: ubuntu-latest

    # Make the three required secrets available to every step
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID:   ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD:  ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest     # pin a version if you want reproducibility

      - name: Link Supabase project
        run: supabase link --project-ref "$SUPABASE_PROJECT_ID"

      # Runs migrations; the CLI is non-interactive in CI as long as the
      # env-vars above are set, so no extra flags are needed.
      - name: Apply migrations
        run: supabase db push

      - name: Show migration status
        run: supabase db status
