name: Run Supabase Migrations

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:       # allows manual runs from the Actions tab

jobs:
  migrate:
    runs-on: ubuntu-latest

    # Expose Supabase credentials to every step in the job
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID:   ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD:  ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Links the local repo to your cloud project (no prompts in CI)
      - name: Link Supabase project
        run: supabase link --project-ref "$SUPABASE_PROJECT_ID"

      # Applies any new migration files in supabase/migrations/
      - name: Apply migrations
        run: supabase db push --no-confirm        # --no-confirm avoids Y/n prompts

      # Optional – shows status after applying
      - name: Show migration status
        run: supabase db status
